## Importar el modulo


In [1]:
include("function.jl")

Main.ProblemFunction

In [2]:
using .ProblemFunction

Variables del lider

In [3]:
lider_vars=["x_1","x_2"]

2-element Vector{String}:
 "x_1"
 "x_2"

Variables del follower

In [4]:
follower_vars=["y_1","y_2"]

2-element Vector{String}:
 "y_1"
 "y_2"

Concatenar las variables de los dos niveles

In [5]:
problem_vars_str=vcat(lider_vars,follower_vars)

4-element Vector{String}:
 "x_1"
 "x_2"
 "y_1"
 "y_2"

convertir a variables de Symbolics

In [6]:
problem_vars=map(ProblemFunction.convert_Symbol_to_symbolic_num,problem_vars_str)

4-element Vector{Symbolics.Num}:
 x_1
 x_2
 y_1
 y_2

## Declarar la funcion del lider

In [7]:
leader_func_str::String="((x_1^2)*(y_1^2)*(y_2))+x_2"

"((x_1^2)*(y_1^2)*(y_2))+x_2"

### Definir restricciones del lider

In [8]:
g_1=Def_Restriction_init("x_1+y_2-y_1==9",J_0_g,Eq,true,0.3,0,0)

Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Eq
------------------------------
Conjunto de indices al que pertenece J_0_g 
------------------------------
Es de la funcion lider true
------------------------------
El valor de miu es 0.3
------------------------------
El valor de beta es 0
------------------------------
El valor de lambda es 0
------------------------------


Crear un vector con las G_s

In [9]:
g_s=[g_1]

1-element Vector{Def_Restriction}:
 

Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Eq
------------------------------
Conjunto de indices al que pertenece J_0_g 
------------------------------
Es de la funcion lider true
------------------------------
El valor de miu es 0.3
------------------------------
El valor de beta es 0
------------------------------
El valor de lambda es 0
------------------------------
Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Eq
------------------------------
Conjunto de indices al que pertenece J_0_g 
------------------------------
Es de la funcion lider true
------------------------------
El valor de miu es 0.3
------------------------------
El valor de beta es 0
------------------------------
El valor de lambda es 0
------------------------------
Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Eq
------------------------------
Conjunto de ind

## Definir el nivel inferior

### Funcion del follower

In [10]:
Follower_str_expr="((x_1^2)*(y_1^2)*(y_2))+x_2"

"((x_1^2)*(y_1^2)*(y_2))+x_2"

#### Restricciones del follower

In [11]:
v_1=Def_Restriction_init("((x_1^2)*(y_1^2)*(y_2))+x_2==0",J_Ne_L0_v,Lt,false,0,0,1)

Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Lt
------------------------------
Conjunto de indices al que pertenece J_Ne_L0_v 
------------------------------
Es de la funcion lider false
------------------------------
El valor de miu es 0
------------------------------
El valor de beta es 0
------------------------------
El valor de lambda es 1
------------------------------


Agrupar las $v_s$ en un vector

In [12]:
v_s=[v_1]

1-element Vector{Def_Restriction}:
 

Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Lt
------------------------------
Conjunto de indices al que pertenece J_Ne_L0_v 
------------------------------
Es de la funcion lider false
------------------------------
El valor de miu es 0
------------------------------
El valor de beta es 0
------------------------------
El valor de lambda es 1
------------------------------
Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Lt
------------------------------
Conjunto de indices al que pertenece J_Ne_L0_v 
------------------------------
Es de la funcion lider false
------------------------------
El valor de miu es 0
------------------------------
El valor de beta es 0
------------------------------
El valor de lambda es 1
------------------------------
Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Lt
------------------------------
Conjunto 

#### Definir los Lambdas

In [13]:
lambdas=Dict(v_1=>0)

Dict{Def_Restriction, Int64} with 1 entry:
   => 0

Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Lt
------------------------------
Conjunto de indices al que pertenece J_Ne_L0_v 
------------------------------
Es de la funcion lider false
------------------------------
El valor de miu es 0
------------------------------
El valor de beta es 0
------------------------------
El valor de lambda es 1
------------------------------


Definir los $\beta_j$

In [14]:
beta_j=Dict(v_1=>0.1)

Dict{Def_Restriction, Float64} with 1 entry:
   => 0.1

Mostrar las definiciones de las restricciones
------------------------------
Tipo de restriccion Lt
------------------------------
Conjunto de indices al que pertenece J_Ne_L0_v 
------------------------------
Es de la funcion lider false
------------------------------
El valor de miu es 0
------------------------------
El valor de beta es 0
------------------------------
El valor de lambda es 1
------------------------------


#### Declarar $\alpha$  tiene dimension de y

In [15]:
alpha=[0.2]

1-element Vector{Float64}:
 0.2

## Ver condiciones para la factibilidad

#### Punto: $x_1 = 3$ $x_2 = 2 $ $y_1=5$ $y_2=2$

In [16]:
point=Dict("x_1"=>1,"x_2"=>1,"y_1"=>1,"y_2"=>1)

Dict{String, Int64} with 4 entries:
  "x_1" => 1
  "x_2" => 1
  "y_2" => 1
  "y_1" => 1

In [17]:
opt_problem=Fix_Restrictions(leader_func_str,g_s,Follower_str_expr,v_s,point)

Mostrar la funcion objetivo del lider
Nombre de variables: [:x_1, :y_1, :y_2, :x_2] 
Expresion en str: ((x_1^2)*(y_1^2)*(y_2))+x_2
Expresion parseada x_2 + (x_1^2)*(y_1^2)*y_2
Punto a evaluar Dict("x_1" => 1, "x_2" => 1, "y_2" => 1, "y_1" => 1)
Valor de evaluacion 2
Es funcion lider true
------------------------------
Mostrar las restricciones del lider
++++++++++++++++++++++++++++++
Restriccion 1
Nombre de variables: [:x_1, :y_1, :y_2] 
Expresion en str: x_1+y_2-y_1==9
Expresion parseada -9 + x_1 - y_1 + y_2
Punto a evaluar Dict("x_1" => 1, "x_2" => 1, "y_2" => 1, "y_1" => 1)
Valor de evaluacion -8
Valor constante añadida 8
Tipo de restriccion Eq
Cjt ind que pertenece J_0_g
El valor de miu es 0.3
El valor de Beta es 0
El valor de lambda es 0
++++++++++++++++++++++++++++++
------------------------------
Mostrar funcion del follower
Nombre de variables: [:x_1, :y_1, :y_2, :x_2] 
Expresion en str: ((x_1^2)*(y_1^2)*(y_2))+x_2
Expresion parseada x_2 + (x_1^2)*(y_1^2)*y_2
Punto a evaluar Di

Vector Gradiente de $F$

In [18]:
leader_fun=opt_problem.leader_fun

Nombre de variables: [:x_1, :y_1, :y_2, :x_2] 
Expresion en str: ((x_1^2)*(y_1^2)*(y_2))+x_2
Expresion parseada x_2 + (x_1^2)*(y_1^2)*y_2
Punto a evaluar Dict("x_1" => 1, "x_2" => 1, "y_2" => 1, "y_1" => 1)
Valor de evaluacion 2
Es funcion lider true


expresion parseada del lider

In [19]:
leader_expr=leader_fun.expr

x_2 + (x_1^2)*(y_1^2)*y_2

In [20]:
using Symbolics

In [21]:
typeof(leader_expr)

Num

In [22]:
typeof(problem_vars)

Vector{Num} (alias for Array{Num, 1})

#### Calculadora de gradientes de una lista de vectores


In [23]:
function gradient_from_vector_func(funcs::Vector{Num},vars::Vector{Num})
    resp=[]
    for item in funcs
        push!(resp,ProblemFunction.Symbolics.gradient(item,vars))
    end
    return resp
end

gradient_from_vector_func (generic function with 1 method)

In [24]:
leader_expr

x_2 + (x_1^2)*(y_1^2)*y_2

In [25]:
grad_F=gradient_from_vector_func([leader_expr],problem_vars)[1]

4-element Vector{Num}:
 2x_1*(y_1^2)*y_2
                1
 2(x_1^2)*y_1*y_2
  (x_1^2)*(y_1^2)

### Calcular los gradientes de las $g_s$

In [26]:
g_s_expr=map(i ->i.expr,opt_problem.leader_restrictions)

1-element Vector{Num}:
 -9 + x_1 - y_1 + y_2

In [27]:
grad_g_s=gradient_from_vector_func(g_s_expr,problem_vars)

1-element Vector{Any}:
 Num[1, 0, -1, 1]

In [28]:
typeof(problem_vars)

Vector{Num} (alias for Array{Num, 1})

Valor de la sumatoria de los vectores de las $g_s$ por su $miu_j$ correspondiente

In [29]:
problem_vars

4-element Vector{Num}:
 x_1
 x_2
 y_1
 y_2

In [30]:
ww=MyParser.substitute_point_in_vector(problem_vars,opt_problem.point)

4-element Vector{Num}:
 1
 1
 1
 1

In [31]:
typeof(ww)

Vector{Num} (alias for Array{Num, 1})

In [32]:
function calculate_g_s_active_mui_factor(opt_problem::Optimization_Problem,problem_vars::Vector{Num})::Vector{Num}
    vector_value=zeros(length(problem_vars))
    for g in opt_problem.leader_restrictions
        # Ahora debe sacar su expresion
        g_expr=g.expr
        grad_g=ProblemFunction.Symbolics.gradient(g_expr,problem_vars)
        vector_result=MyParser.substitute_point_in_vector(grad_g,opt_problem.point)
        vector_result=vector_result*g.miu
        vector_value+=vector_result
    end
    return vector_value

end

calculate_g_s_active_mui_factor (generic function with 1 method)

### Vector de la suma de las $g_s$ cada una multiplicada por su miu

In [33]:
g_s_sum=calculate_g_s_active_mui_factor(opt_problem,problem_vars)

4-element Vector{Num}:
  0.3
  0.0
 -0.3
  0.3

In [34]:
g_s_sum

4-element Vector{Num}:
  0.3
  0.0
 -0.3
  0.3

In [35]:
typeof(g_s_sum)

Vector{Num} (alias for Array{Num, 1})

In [36]:
function Calculate_diff_ys_xsys(func_expr::Num,vars::Vector{Num},vars_y::Vector{Num},point::Dict)
    A=Symbolics.gradient(func_expr,vars_y)
    # Calcular el gradiente de cada expresión en la matriz
    grad_matrix = [Symbolics.gradient(A[i, j], vars) for i in 1:size(A, 1), j in 1:size(A, 2)]
    concat_matrix= hcat(grad_matrix...)
    return MyParser.substitute_point_in_vector(concat_matrix,opt_problem.point)
end

Calculate_diff_ys_xsys (generic function with 1 method)

In [37]:
@variables x_1,x_2,y_1,y_2

4-element Vector{Num}:
 x_1
 x_2
 y_1
 y_2

In [38]:
func_expr=((x_1^2)*(y_1^2)*y_2)+x_2

x_2 + (x_1^2)*(y_1^2)*y_2

In [39]:
A=Calculate_diff_ys_xsys(func_expr,[x_1,x_2,y_1,y_2],[y_1,y_2],opt_problem.point)

4×2 Matrix{Num}:
 4  2
 0  0
 2  2
 2  0

Cuantas columnas tiene

In [40]:
size(A,2)

2

Calcular la der de F 

In [41]:
function calculate_diff_F_xy(opt_problem::Optimization_Problem,problem_vars::Vector{Num})
    # Obtener la struct Func del lider
    leader_fun=opt_problem.leader_fun
    # Obtener la expr de la funcion del lider
    leader_expr=leader_fun.expr
    # Hallar el gradiente de F
    grad_F=gradient_from_vector_func([leader_expr],problem_vars)[1]
    # Sustituir el gradiente en el punto
    grad_val=MyParser.substitute_point_in_vector(grad_F,opt_problem.point)
    return grad_val

end

calculate_diff_F_xy (generic function with 1 method)

In [42]:
calculate_diff_F_xy(opt_problem,problem_vars)

4-element Vector{Num}:
 2
 1
 2
 1

Calcular la zona de la diff x,y de y de f + 

Calcular la zona que tiene que ver con f y la v_i elegida

In [43]:
function calculate_f_grad_xy_of_x(opt_problem::ProblemFunction.Optimization_Problem,problems_vars::Vector{Num},ys_vars::Vector{Num})::Matrix
    f_expr=opt_problem.follower_fun.expr
    point=opt_problem.point
    return Calculate_diff_ys_xsys(f_expr,problems_vars,ys_vars,point)

end 

calculate_f_grad_xy_of_x (generic function with 1 method)

In [44]:
calculate_f_grad_xy_of_x(opt_problem,problem_vars,[y_1,y_2])

4×2 Matrix{Num}:
 4  2
 0  0
 2  2
 2  0

Ahora de la v_i seleccionada hacer el (grad * si lambda )* $\alpha$

In [45]:

y = 0
@assert y < 5 "El valor de y debería ser menor que 5"  # Lanza un AssertionError con el mensaje especificado.

In [46]:
function calculate_select_vi_der_xy_of_x_dot_lambda_alpha(opt_problem::ProblemFunction.Optimization_Problem,index_vi::Int64,problems_vars::Vector{Num},ys_vars::Vector{Num},alpha::Vector)
# Ver si la cant de variables y coincide con la dimension de alpha
ys_len=length(ys_vars)
alpha_len=length(alpha)
@assert ys_len==alpha_len "El length de alpha es $alpha_len y el de las ys es $ys_len y deben ser iguales"
# Tomar la restriccion que se quiere
vi=opt_problem.follower_restrictions[index_vi]
# Tomar la expresion de la funcion de restriccion
vi_expr=vi.expr
println(vi_expr)
# Tomar el punto a evaluar
point=opt_problem.point
# Calcular y evaluar el gradiente 
vi_grad_val=Calculate_diff_ys_xsys(vi_expr,problems_vars,ys_vars,point)
# Tomar el lambda de ese restriccion
lambda_i=vi.lambda
# Multiplicar el gradiente evaluado por lambda
vi_lambda=vi_grad_val*lambda_i
# Multiplicar Todo por alpha
return vi_lambda*alpha


end


calculate_select_vi_der_xy_of_x_dot_lambda_alpha (generic function with 1 method)

In [47]:
ys_vars=[y_1,y_2]

2-element Vector{Num}:
 y_1
 y_2

In [48]:
calculate_select_vi_der_xy_of_x_dot_lambda_alpha(opt_problem,1,problem_vars,ys_vars,[2,4])

x_2 + (x_1^2)*(y_1^2)*y_2


4-element Vector{Num}:
 16
  0
 12
  4

Calcular sumatoria de gradiente en xy de $v_j * \beta_j$

In [56]:
@enum FactorType begin
    miu_
    lambda_
    beta_
end

In [57]:
lambda_

lambda_::FactorType = 1

In [58]:
function get_factor_value(restr_func::ProblemFunction.Restriction_Func,factor_type::FactorType)
if factor_type == miu_
    return restr_func.miu
elseif factor_type == lambda_
    return restr_func.lambda
elseif factor_type == beta_
    return restr_func.beta
else
    throw(ArgumentError("El tipo de factor $factor_type es inválido"))

end

end

get_factor_value (generic function with 1 method)

In [ ]:
function calculate_g_s_active_mui_factor(restrictions::Vector{ProblemFunction.Restriction_Func},problem_vars::Vector{Num},point::Vector,factor_type::FactorType)::Vector{Num}
    vector_value=zeros(length(problem_vars))
    for restriction in restrictions
        # Ahora debe sacar su expresion
        restr_expr=restriction.expr
        grad_restriction=ProblemFunction.Symbolics.gradient(restr_expr,problem_vars)
        vector_result=MyParser.substitute_point_in_vector(grad_restriction,point)
        # Tomar el factor necesario para sumar
        factor=get_factor_value(restriction,factor_type)
        vector_result=vector_result* factor
        vector_value+=vector_result
    end
    return vector_value

end