In [1]:
using Symbolics

In [2]:
a=zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [3]:
using LinearAlgebra

# Definir el vector
v = [3, 4]

# Calcular la norma dos
norma = norm(v)

# Mostrar el resultado
println("La norma dos del vector es: ", norma)

La norma dos del vector es: 5.0


In [25]:
alpha=v

2-element Vector{Int64}:
 3
 4

In [4]:
include("parser.jl")

Main.MyParser

In [5]:
using ..MyParser

In [6]:
expr_str="(x_1^2)+x_2+y_1==0"

"(x_1^2)+x_2+y_1==0"

In [7]:
 # Tomar el nombre de las variables
 vars_name::Vector{Symbol} = MyParser.extract_variable_names(expr_str)
 # Registrar las variables
 MyParser.add_to_symbolics(vars_name)
 # Obtener las expresiones

In [8]:
left, rigth = MyParser.separate_equation(expr_str)
#TODO: Despues añadir aca la logica para virar las inecuaciones
# Nueva expresion de la ecuación
new_expr = left - rigth

x_2 + y_1 + x_1^2

Hallar las derivadas respecto a y

In [9]:
function convert_Symbol_to_symbolic_num(symbol::Symbol)::Symbolics.Num
    # Devuelve una lista de Symbolics.Num y solo quiero devolver el primer elemento
    return Symbolics.variables(symbol)[1]

end
function convert_Symbol_to_symbolic_num(symbol::String)::Num
    return Symbolics.variables(symbol)[1]
    
end



convert_Symbol_to_symbolic_num (generic function with 2 methods)

In [39]:
convert_Symbol_to_symbolic_num.(["x_1","x_2","y_1","y_2"])


4-element Vector{Num}:
 x_1
 x_2
 y_1
 y_2

In [10]:
vars=map(convert_Symbol_to_symbolic_num,["x_1","x_2","y_1","y_2"])

4-element Vector{Num}:
 x_1
 x_2
 y_1
 y_2

In [18]:
y_vars=map(convert_Symbol_to_symbolic_num,["y_1","y_2"])

2-element Vector{Num}:
 y_1
 y_2

In [11]:
function gradient_from_vector_func(funcs::Vector{Num},vars::Vector{Num})
    resp=[]
    for item in funcs
        push!(resp,Symbolics.gradient(item,vars))
    end
    return resp
end


gradient_from_vector_func (generic function with 1 method)

In [19]:
grad=gradient_from_vector_func([new_expr],y_vars)

1-element Vector{Any}:
 Num[1, 0]

In [21]:
function eval_point(expr,point::Dict)
    # Convertir el diccionario desde strings a Symbolos
    new_dicc=Dict(convert_Symbol_to_symbolic_num(key) => point[key] for key in keys(point))
    # Sustituir la expresion por el punto Para substitute se tiene que enviar en forma de tupla
    return substitute.(expr,(new_dicc,))[1]
    
end

eval_point (generic function with 1 method)

In [22]:
point=Dict("x_1"=>1,"x_2"=>1,"y_1"=>1,"y_2"=>1)

Dict{String, Int64} with 4 entries:
  "x_1" => 1
  "x_2" => 1
  "y_2" => 1
  "y_1" => 1

In [23]:
grad_eval=eval_point(grad,point)

2-element Vector{Int64}:
 1
 0

Hacer el gradiente negativo


In [24]:
grad_eval=-grad_eval

2-element Vector{Int64}:
 -1
  0

In [26]:
alpha

2-element Vector{Int64}:
 3
 4

In [32]:
bj=dot(grad_eval,alpha)/norma

-0.6

In [41]:
length(point)

4

In [43]:
length(Dict())

0

In [44]:
function calculate_grad_and_evaluate_in_point(func_expr,point::Dict,vars_grad::Vector{Num})::Vector{Number}
    grad=Symbolics.gradient(func_expr,vars_grad)
    return MyParser.substitute_point_in_vector(grad,point)
    end

calculate_grad_and_evaluate_in_point (generic function with 1 method)

In [45]:
calculate_grad_and_evaluate_in_point(new_expr,point,y_vars)

2-element Vector{Number}:
 1
 0

In [46]:
a=[1,2,3]

3-element Vector{Int64}:
 1
 2
 3

Base.Meta.ParseError: ParseError:
# Error @ /home/fvsb/projects/Tesis/evaluator/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_X41sdnNjb2RlLXJlbW90ZQ==.jl:1:2
+.a
#╙ ── invalid identifier